# encoding: utf-8

class HttpCode(object):
    HTTP_SUCCESS = 200
    HTTP_ACCEPED = 201
    HTTP_BAD_REQUEST = 400
    HTTP_UNAUTHORIZED = 401
    HTTP_FORBIDDEN = 403
    HTTP_NOT_FOUND = 404
    HTTP_METHOD_NOT_ALLOWED = 405
    HTTP_APPLICATION_ERROR = 500
    HTTP_NOT_IMPLEMENTED = 501